project:
  type: website

website:
  title: "Md Sahadat Hossain - MBA Portfolio"
  page-navigation: false
  search: false
  navbar: false

format:
  html:
    theme: cosmo
    toc: false
    css: styles.css
    embed-resources: true



